# Предсказание цен на жилье с использованием собственной реализации модели линейной регрессии

- Датасет: https://www.kaggle.com/competitions/two-sigma-connect-rental-listing-inquiries/overview

# 1. Imports

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn as sk
from tqdm import tqdm

from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

from help_functions import *
from my_linreg import MyLinearRegression

# 2. Preprocessing

In [2]:
!gdown 1T5lTGqpn4kyMzTTSgI0SHG-PI0aYceV9 # train.json.zip

Downloading...
From: https://drive.google.com/uc?id=1T5lTGqpn4kyMzTTSgI0SHG-PI0aYceV9
To: /content/train.json.zip
100% 21.0M/21.0M [00:00<00:00, 126MB/s]

In [3]:
zip_files = ["/content/train.json.zip"]
unzip_files(zip_files)

In [4]:
train_data = pd.read_json("/content/train.json")
train_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 49352 entries, 4 to 124009
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   bathrooms        49352 non-null  float64
 1   bedrooms         49352 non-null  int64
 2   building_id      49352 non-null  object
 3   created          49352 non-null  object
 4   description      49352 non-null  object
 5   display_address  49352 non-null  object
 6   features         49352 non-null  object
 7   latitude         49352 non-null  float64
 8   listing_id       49352 non-null  int64
 9   longitude        49352 non-null  float64
 10  manager_id       49352 non-null  object
 11  photos           49352 non-null  object
 12  price            49352 non-null  int64
 13  street_address   49352 non-null  object
 14  interest_level   49352 non-null  object
dtypes: float64(3), int64(3), object(9)
memory usage: 6.0+ MB

Обрабатываем фичи по оптимальному пайплайну из соседнего блокнота ():

In [5]:
processed_data = run_preprocessing(train_data)
processed_data[:3]

Ванны и спальни почищены от выбросов.
Всё assert-ы прошли - признаки из features энкодированы корректно.

,bathrooms,bedrooms,latitude,longitude,price,interest_level,elevator,hardwoodfloors,catsallowed,dogsallowed,...,pre-war,roofdeck,outdoorspace,diningroom,highspeedinternet,balcony,swimmingpool,newconstruction,terrace,exclusive
0,1,1,40.7108,-73.9539,2400,1,0,1,1,1,...,1,0,0,1,0,0,0,0,0,0
1,1,2,40.7513,-73.9722,3800,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,2,40.7575,-73.9625,3495,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0

# 4. Models implementation — Linear regression

- Initialize the random number generator with a seed of 42.
- Implement a Python class for a linear regression algorithm with two basic methods — fit and predict. Use stochastic gradient descent (SGD) to find optimal model weights. For better understanding, we recommend implementing separate versions of the algorithm with the analytical solution and non-stochastic gradient descent under the hood.
- What is determenistic model? Make SGD determenistic. - воспроизводимые результаты при одинаковых начальных и конечных условиях
- Define the R squared (R2) coefficient and implement a function to calculate it. - коэфф детерминации

In [6]:
def mean_absolute_error(y_true, y_pred):
    return np.mean(np.abs(y_true - y_pred))

def root_mean_squared_error(y_true, y_pred):
    return np.sqrt(np.mean((y_true - y_pred) ** 2))

def r_squared(y_true, y_pred):
    ss_res = np.sum((y_true - y_pred) ** 2)
    ss_tot = np.sum((y_true - np.mean(y_true)) ** 2)
    return 1 - (ss_res / ss_tot)

# 5. Training

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_val, Y_train, Y_val = train_test_split(processed_data.drop("price", axis=1),
                                                   processed_data["price"],
                                                   test_size=0.2,
                                                   random_state=42,
                                                   stratify = processed_data["interest_level"])
print(X_train.shape, Y_train.shape)
print(X_val.shape, Y_val.shape)

(38674, 25) (38674,)
(9669, 25) (9669,)

In [8]:
X_train.columns

Index(['bathrooms', 'bedrooms', 'latitude', 'longitude', 'interest_level',
       'elevator', 'hardwoodfloors', 'catsallowed', 'dogsallowed', 'doorman',
       'dishwasher', 'laundryinbuilding', 'nofee', 'fitnesscenter',
       'laundryinunit', 'pre-war', 'roofdeck', 'outdoorspace', 'diningroom',
       'highspeedinternet', 'balcony', 'swimmingpool', 'newconstruction',
       'terrace', 'exclusive'],
      dtype='object')

Добавим признак cluster_label:

In [9]:
# доб cluster_label
from sklearn.cluster import KMeans
kmeans_model = KMeans(n_clusters=40, init="k-means++", random_state=42)
X_train_ll = X_train[["latitude", "longitude"]]
X_val_ll = X_val[["latitude", "longitude"]]
X_train["cluster_label"] = kmeans_model.fit_predict(X_train_ll)
X_val["cluster_label"] = kmeans_model.predict(X_val_ll)

In [10]:
# трансформация таргета - log
Y_train_log = np.log1p(Y_train)
Y_val_log = np.log1p(Y_val)
Y_train_log.shape

(38674,)

In [11]:
# добавим признак логарифма расстояния от центра
center = (40.7128, -74.0060)
X_train['dist'] = np.log(((X_train['latitude']-center[0])**2 + (X_train['longitude']-center[1])**2)**0.5 + 1)
X_val['dist'] = np.log(((X_val['latitude']-center[0])**2 + (X_val['longitude']-center[1])**2)**0.5 + 1)

In [12]:
# отбираем важные фичи по кэтбусту, как в соседнем блокноте
X_train_new = X_train[["bathrooms", "bedrooms", "latitude", "longitude", "dist","doorman", "interest_level","cluster_label", "fitnesscenter", "elevator", "laundryinunit"]].copy()
X_val_new = X_val[["bathrooms", "bedrooms", "latitude", "longitude", "dist", "doorman", "interest_level","cluster_label", "fitnesscenter", "elevator", "laundryinunit"]].copy()

- Наиболее оптимальным для линейной регрессии оказался следующий пайплайн:
- полиномиальные фичи от логарифма расстояния, кол-ва ванн и спален;
- обработка "interest_level", "cluster_label" как категориальных фич через OHE;
- отобранные на кэтбусте по важности признаки из топ20: "doorman", "fitnesscenter", "elevator", "laundryinunit" (они уже энкодированы как 0/1 после препроцессинга).

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline

preprocessor = ColumnTransformer([
    ('poly', PolynomialFeatures(2), ["bathrooms", "bedrooms", 'dist']),
    ('cat', OneHotEncoder(drop='first', sparse_output=False), ["interest_level", "cluster_label"]),
    ('other', 'passthrough', ["doorman", "latitude", "longitude", "fitnesscenter", "elevator", "laundryinunit"])
])

- Make predictions with your algorithm and estimate the model with MAE, RMSE and R2 metrics.

In [14]:
def evaluate_models(X_train, Y_train, X_test, Y_test, models=None, modes=None, log_y=True):

    dtypes = {'model': 'object', 'train': 'float64', 'test': 'float64'}
    result_MAE = pd.DataFrame(columns=['model', 'train', 'test']).astype(dtypes)
    result_MSE = pd.DataFrame(columns=['model', 'train', 'test']).astype(dtypes)
    result_r2 = pd.DataFrame(columns=['model', 'train', 'test']).astype(dtypes)
    trained_models = {}

    if models is None:
        if modes is None:
            modes = ['analytical', 'stochastic', 'non-stochastic']

        models = {}
        for mode in modes:
            models[f'my_linreg_{mode}'] = MyLinearRegression(mode=mode)

    for model_name, model in models.items():
        if hasattr(model, 'fit') and hasattr(model, 'predict'):

            model.fit(X_train, Y_train)
            trained_models[model_name] = model

            predicted_train = model.predict(X_train)
            predicted_test = model.predict(X_test)

            _Y_train = Y_train.copy()
            _Y_test = Y_test.copy()

            if log_y:
              # возвращаем к первоначальному масштабу
              predicted_train  = np.expm1(predicted_train)
              predicted_test = np.expm1(predicted_test)
              _Y_train = np.expm1(_Y_train)
              _Y_test = np.expm1(_Y_test)

            train_mae = mean_absolute_error(_Y_train, predicted_train)
            test_mae = mean_absolute_error(_Y_test, predicted_test)

            train_rmse = root_mean_squared_error(_Y_train, predicted_train)
            test_rmse = root_mean_squared_error(_Y_test, predicted_test)

            train_r2 = r_squared(_Y_train, predicted_train)
            test_r2 = r_squared(_Y_test, predicted_test)

            new_mae = pd.DataFrame({
                'model': [model_name],
                'train': [train_mae],
                'test': [test_mae]
            })

            new_rmse = pd.DataFrame({
                'model': [model_name],
                'train': [train_rmse],
                'test': [test_rmse]
            })

            new_r2 = pd.DataFrame({
                'model': [model_name],
                'train': [train_r2],
                'test': [test_r2]
            })

            result_MAE = pd.concat([result_MAE, new_mae], ignore_index=True)
            result_MSE = pd.concat([result_MSE, new_rmse], ignore_index=True)
            result_r2 = pd.concat([result_r2, new_r2], ignore_index=True)
        else:
            print(f"Модель {model_name} не имеет методов fit и predict, пропускаем")

    return result_MAE, result_MSE, result_r2, trained_models

In [15]:
mlinreg = MyLinearRegression(mode='analytical')
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('scaler', StandardScaler()),
    ('regressor', mlinreg)
])

pipeline.fit(X_train_new, Y_train_log)
predictions_mlinreg = pipeline.predict(X_val_new)

- Initialize LinearRegression() from sklearn.linear_model, fit the model, and predict the training and test parts as in the previous lesson.
- Compare the quality metrics and make sure the difference is small (between your implementations and sklearn).
- Store the metrics as in the previous lesson in a table with columns model, train, test for MAE table, RMSE table, and R2 coefficient.

In [16]:
from sklearn.linear_model import LinearRegression

linreg = LinearRegression(fit_intercept=True)
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('scaler', StandardScaler()),
    ('regressor', linreg)
])

pipeline.fit(X_train_new, Y_train_log)
predictions_linreg = pipeline.predict(X_val_new)

In [17]:
are_identical = np.allclose(predictions_mlinreg, predictions_linreg, rtol=1e-5, atol=1e-5)
# absolute(a - b) <= (atol + rtol * absolute(b))
print(f"Результаты идентичны: {are_identical}")

if not are_identical:
    #находим отличающиеся индексы
    diff_indices = np.where(differences > 1e-5)[0]
    print(f"Количество значимых различий: {len(diff_indices)}")
    print(f"Индексы с различиями: {diff_indices[:10]}")

Результаты идентичны: True

In [18]:
train_pred = pipeline.predict(X_train_new)
train_pred_orig  = np.expm1(train_pred)
train_mae = mean_absolute_error(Y_train, train_pred_orig)
train_mae

np.float64(539.0903532412051)

In [19]:
val_pred = pipeline.predict(X_val_new)
val_pred_orig = np.expm1(val_pred)
valid_mae = mean_absolute_error(Y_val, val_pred_orig)
valid_mae

np.float64(528.4870859332907)

- Для режима  "analytical" и схожих параметрах запуска (в моем классе линрег intercept=True по дефолту) получились одинаковые предсказания на валидационной выборке.
- Кроме того, метрики MAE совпали с аналогичными из предыдущего блокнота - значит пайплайн обработки данных и обучения моделей воспроизводим.

In [20]:
# посмотрим на другие режимы работы моего класса - создадим пайплайн для трансформации данных перед подачей в модель
from sklearn.pipeline import make_pipeline

feature_transformer = make_pipeline(preprocessor, StandardScaler())
X_train_final = feature_transformer.fit_transform(X_train_new)
X_val_final = feature_transformer.transform(X_val_new)

In [21]:
models_dict = {
    'my_linreg': MyLinearRegression(mode='analytical'),
    'my_linreg_GD': MyLinearRegression(mode='non-stochastic'),
    'my_linreg_SGD': MyLinearRegression(mode='stochastic', lr=0.0001, iters=10000),
    'sk-linreg': LinearRegression()
    }

result_base_MAE, result_base_MSE, result_base_r2, trained_models_base = evaluate_models(
    X_train_final, Y_train_log, X_val_final, Y_val_log,
    models=models_dict
)

- Для стохастического спуска пришлось уменьшить lr (был взрыв градиентов) и увеличить кол-во итераций (для компенсации скорости сходимости)

In [22]:
result_base_MAE

           model       train        test
0      my_linreg  539.090353  528.487086
1   my_linreg_GD  564.590623  555.866597
2  my_linreg_SGD  590.521721  579.872965
3      sk-linreg  539.090353  528.487086

In [23]:
result_base_MSE

           model        train        test
0      my_linreg   864.616528  829.321481
1   my_linreg_GD   920.392005  883.315457
2  my_linreg_SGD  1001.026311  956.213276
3      sk-linreg   864.616528  829.321481

In [24]:
result_base_r2

           model     train      test
0      my_linreg  0.704750  0.718456
1   my_linreg_GD  0.665429  0.680602
2  my_linreg_SGD  0.604238  0.625708
3      sk-linreg  0.704750  0.718456

In [25]:
dtypes = {'model': 'object', 'train': 'float64', 'test': 'float64'}
final_MAE = pd.DataFrame(columns=['model', 'train', 'test']).astype(dtypes)
final_MSE = pd.DataFrame(columns=['model', 'train', 'test']).astype(dtypes)
final_r2 = pd.DataFrame(columns=['model', 'train', 'test']).astype(dtypes)

In [26]:
final_MAE = pd.concat([final_MAE, result_base_MAE[result_base_MAE['model'] == 'sk-linreg']])
final_MSE = pd.concat([final_MSE, result_base_MSE[result_base_MSE['model'] == 'sk-linreg']])
final_r2 = pd.concat([final_r2, result_base_r2[result_base_r2['model'] == 'sk-linreg']])

- Все режимы работают примерно одинаково по качеству, дают сопоставимые метрики mae, rmse, r2.
- Лучше всего показывает себя аналитическое решение (для градиентов нужно подбирать параметры темпа обучения и кол-ва итераций)

# 5. Regularized models implementation — Ridge, Lasso, ElasticNet

- Implement Ridge, Lasso, ElasticNet algorithms: extend the loss function with L2, L1 and both regularizations accordingly. - см. класс MyLinearRegression выше
- Make predictions with your algorithm and estimate the model with MAE, RMSE and R2 metrics.
- Initialize Ridge(), Lasso(), and ElasticNet() from sklearn.linear_model, fit the model, and make predictions for the training and test samples as in the previous lesson.
- Compare quality metrics and make sure the difference is small (between your implementations and sklearn).
- Store the metrics as in the previous lesson in a table with columns model, train, test for MAE table, RMSE table, and R2 coefficient.

In [27]:
from sklearn.linear_model import Ridge, Lasso, ElasticNet

In [28]:
def get_models_dict(alpha=0.1, lr=0.005, iters=5000, l1_ratio=0.5, name=None, clip_value=None):
    models_dict = {}
    name_suffix = f"_{name}" if name is not None else ""

    for penalty in [None, 'lasso', 'ridge', 'elasticnet']:
        for mode in ["analytical", 'stochastic', 'non-stochastic']:
            if mode is None:
                penalty_used = None
                penalty_str = "nopenalty"
            else:
                penalty_used = penalty
                penalty_str = "nopenalty" if penalty is None else penalty

            mode_str = "analytical" if mode is None else mode
            model_name = f"my_linreg_{mode_str}_{penalty_str}"
            models_dict[model_name] = MyLinearRegression(mode=mode, penalty=penalty_used, alpha=alpha, lr=lr, iters=iters, l1_ratio=l1_ratio, clip_value=clip_value)

    models_dict[f'sk_linreg{name_suffix}'] = LinearRegression(fit_intercept=True)
    models_dict[f'sk_lasso{name_suffix}'] = Lasso(alpha=0.1)
    models_dict[f'sk_ridge{name_suffix}'] = Ridge(alpha=0.1)
    models_dict[f'sk_elasticnet{name_suffix}'] = ElasticNet(alpha=0.1)

    return models_dict

In [29]:
models_dict = get_models_dict(alpha=0.1, lr=0.0001, iters=10000)
result_penalty_MAE, result_penalty_MSE, result_penalty_r2, trained_models_penalty = evaluate_models(
    X_train_final , Y_train_log, X_val_final, Y_val_log,
    models=models_dict
)

In [30]:
result_penalty_MAE

                                  model       train        test
0        my_linreg_analytical_nopenalty  539.090353  528.487086
1        my_linreg_stochastic_nopenalty  587.421436  576.198519
2    my_linreg_non-stochastic_nopenalty  592.529521  580.611628
3            my_linreg_analytical_lasso  539.090353  528.487086
4            my_linreg_stochastic_lasso  753.324035  737.429324
5        my_linreg_non-stochastic_lasso  754.539215  738.765260
6            my_linreg_analytical_ridge  539.090353  528.487086
7            my_linreg_stochastic_ridge  591.239106  580.164359
8        my_linreg_non-stochastic_ridge  590.944195  578.310261
9       my_linreg_analytical_elasticnet  539.090353  528.487086
10      my_linreg_stochastic_elasticnet  667.421754  654.258375
11  my_linreg_non-stochastic_elasticnet  663.130156  650.247268
12                            sk_linreg  539.090353  528.487086
13                             sk_lasso  857.064538  842.414783
14                             sk_ridge  539.288264  528.844743
15                        sk_elasticnet  749.149443  733.631215

In [31]:

result_penalty_MSE

                                  model        train         test
0        my_linreg_analytical_nopenalty   864.616528   829.321481
1        my_linreg_stochastic_nopenalty   984.270201   938.358795
2    my_linreg_non-stochastic_nopenalty  1010.835507   961.654310
3            my_linreg_analytical_lasso   864.616528   829.321481
4            my_linreg_stochastic_lasso  1144.420984  1111.250990
5        my_linreg_non-stochastic_lasso  1148.598109  1114.579513
6            my_linreg_analytical_ridge   864.616528   829.321481
7            my_linreg_stochastic_ridge   994.090315   950.198736
8        my_linreg_non-stochastic_ridge   991.150719   943.648144
9       my_linreg_analytical_elasticnet   864.616528   829.321481
10      my_linreg_stochastic_elasticnet  1059.101763  1021.320707
11  my_linreg_non-stochastic_elasticnet  1046.747859  1010.342831
12                            sk_linreg   864.616528   829.321481
13                             sk_lasso  1282.879609  1253.258488
14                             sk_ridge   865.042402   830.048269
15                        sk_elasticnet  1138.114351  1106.192269

In [32]:
result_penalty_r2

                                  model     train      test
0        my_linreg_analytical_nopenalty  0.704750  0.718456
1        my_linreg_stochastic_nopenalty  0.617377  0.639555
2    my_linreg_non-stochastic_nopenalty  0.596444  0.621437
3            my_linreg_analytical_lasso  0.704750  0.718456
4            my_linreg_stochastic_lasso  0.482734  0.494496
5        my_linreg_non-stochastic_lasso  0.478951  0.491463
6            my_linreg_analytical_ridge  0.704750  0.718456
7            my_linreg_stochastic_ridge  0.609704  0.630402
8        my_linreg_non-stochastic_ridge  0.612009  0.635480
9       my_linreg_analytical_elasticnet  0.704750  0.718456
10      my_linreg_stochastic_elasticnet  0.556985  0.573003
11  my_linreg_non-stochastic_elasticnet  0.567260  0.582133
12                            sk_linreg  0.704750  0.718456
13                             sk_lasso  0.349998  0.357043
14                             sk_ridge  0.704459  0.717962
15                        sk_elasticnet  0.488419  0.499087

In [33]:
models = ['sk_linreg', 'sk_lasso', 'sk_ridge', 'sk_elasticnet']

final_MAE = pd.concat([final_MAE, result_penalty_MAE[result_penalty_MAE['model'].isin(models)]])
final_MSE = pd.concat([final_MSE, result_penalty_MSE[result_penalty_MSE['model'].isin(models)]])
final_r2 = pd.concat([final_r2, result_penalty_r2[result_penalty_r2['model'].isin(models)]])

- Все имплементированные регуляризации работают;
- Полученные метрики незначительно отличаются от аналогичных моделей sklearn (для всех, кроме analytical решения без пенальти) - это связано с особенностями реализаций.
- Но у моей реализации и sklearn есть сходные тенденции: ElasticNet, Lasso - медленнее сходятся на градиентах (сильнее регуляризуют)

# 6. Feature normalization

- First, write several examples of why and where feature normalization is mandatory and vice versa.
- 1) Почему важно нормализовать? - стабильность вычислений, корректная работа алгоритмов регуляризации и алгоритмов, основанных на расстояниях и градиентах
- 2) Когда обязательно регуляризовать? -
Если признаки имеют сильно отличающийся масштаб (например, рост 100-200 и возраст 0-120 или жилая площадь  50-200 м^2 и кол-во комнат 1-5) и на таких данных планируется использовать модели с регуляризацией, градиентным спуском, кластеризации и тд.
- 3) Можно не нормализовать, если признаки уже в сравнимом масштабе или если планируется использовать модели, не учитывающие расстояния и градиенты (навный байес - вероятностная модель, рандом форест и все алгоритмы, основанные на деревьях).
- 4) Еще можно не нормализовать, если признаки бинарные или категориальные - тут уже одинаковый масштаб.

- Let's consider the first of the classical normalization methods — MinMaxScaler. Write a mathematical formula for this method.
Implement your own function or class for MinMaxScaler feature normalization.
- Initialize MinMaxScaler() from sklearn.preprocessing.
- Compare the feature normalization with your own method and with sklearn.

In [34]:
class MyMinMaxScaler:
  def normalize(self, X):
    X = np.array(X, dtype=float)
    X_norm = X.copy()
    for col_index in range(X.shape[1]):
      col_min = X[:, col_index].min()
      col_max = X[:, col_index].max()
      val_range = col_max - col_min
      if val_range == 0:
        X_norm[:, col_index] = 0
      else:
        X_norm[:, col_index] = (X[:, col_index] - col_min) / val_range
    return pd.DataFrame(X_norm)

    # если трушно и матрично
        #X = np.array(X, dtype=float)
        #X_min = np.min(X, axis=0)
        #X_max = np.max(X, axis=0)
        #range_val = X_max - X_min
        #range_val[range_val == 0] = 1
        #return (X - X_min) / range_val

Далее изучаем нормализацию, поэтому используем исходные X_train, X_val (сразу после сплита до пайплайна)

In [35]:
my_minmax = MyMinMaxScaler()
norm_X_train= my_minmax.normalize(X_train[['bathrooms', 'bedrooms']])
norm_X_train.sample(5, random_state=42)

         0      1
38125  0.2  0.375
28946  0.2  0.250
25736  0.2  0.000
11477  0.2  0.125
15983  0.2  0.250

In [36]:
from sklearn.preprocessing import MinMaxScaler
sk_minmax = MinMaxScaler()
sk_minmax.fit(X_train[['bathrooms', 'bedrooms']])
norm_X_MMS_train = pd.DataFrame(sk_minmax.transform(X_train[['bathrooms', 'bedrooms']]))
norm_X_MMS_train.sample(5, random_state=42)

         0      1
38125  0.2  0.375
28946  0.2  0.250
25736  0.2  0.000
11477  0.2  0.125
15983  0.2  0.250

- Repeat the steps for another normalization method StandardScaler.

In [37]:
class MyScaler:
  def z_normalize(self, X):
    X = np.array(X, dtype=float)
    X_mean = np.mean(X, axis=0)
    X_stdev = np.std(X, axis=0) + 1e-10
    # альтернатива X_stdev[X_stdev == 0] = 1.0
    return pd.DataFrame((X - X_mean) / X_stdev)

In [38]:
my_scaler = MyScaler()
norm_X_train = my_scaler.z_normalize(X_train[['bathrooms', 'bedrooms']])
norm_X_train.sample(5, random_state=42)

              0         1
38125 -0.413697  1.331128
28946 -0.413697  0.423831
25736 -0.413697 -1.390764
11477 -0.413697 -0.483467
15983 -0.413697  0.423831

In [39]:
from sklearn.preprocessing import StandardScaler
sk_scaler = StandardScaler()
norm_X_SS_train = pd.DataFrame(sk_scaler.fit_transform(X_train[['bathrooms', 'bedrooms']]))
norm_X_SS_train.sample(5, random_state=42)

              0         1
38125 -0.413697  1.331128
28946 -0.413697  0.423831
25736 -0.413697 -1.390764
11477 -0.413697 -0.483467
15983 -0.413697  0.423831

- Кастомные скейлеры работают идентично скейлерам из sklearn.

# 7. Fit custom and sklearn models with normalized data

- Fit all models — Linear Regression, Ridge, Lasso, and ElasticNet — with MinMaxScaler.
- Fit all models — Linear Regression, Ridge, Lasso, and ElasticNet — with StandardScaler.
- Add all results to our dataframe with metrics on samples.

In [40]:
X_train_new

,bathrooms,bedrooms,latitude,longitude,dist,doorman,interest_level,cluster_label,fitnesscenter,elevator,laundryinunit
10525,1,1,40.7619,-73.9854,0.051877,1,0,5,1,0,0
39089,1,0,40.7382,-73.9965,0.026757,1,0,25,0,1,1
37274,1,2,40.6908,-73.9192,0.085760,0,0,13,0,0,0
29405,1,0,40.7707,-73.9512,0.076703,0,0,9,0,0,0
13755,1,1,40.7397,-73.9817,0.035609,0,0,15,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...
9508,1,1,40.7088,-74.0059,0.003993,1,1,18,0,1,0
10877,1,1,40.7719,-73.9565,0.074264,0,0,9,0,0,0
27246,1,1,40.7897,-73.9734,0.080219,1,0,34,1,1,0
4645,1,2,40.7314,-73.9828,0.029302,1,2,29,1,1,0
20483,1,1,40.7568,-73.9659,0.057827,1,0,26,0,1,0

In [41]:
preprocessor = ColumnTransformer([
    ('poly', PolynomialFeatures(2), ["bathrooms", "bedrooms", 'dist']),
    ('cat', OneHotEncoder(drop='first', sparse_output=False), ["interest_level", "cluster_label"]),
    ('other', 'passthrough', ["doorman", "latitude", "longitude", "fitnesscenter", "elevator", "laundryinunit"])
])

In [42]:
feature_transformer = make_pipeline(preprocessor, MinMaxScaler())
X_train_final = feature_transformer.fit_transform(X_train_new)
X_val_final = feature_transformer.transform(X_val_new)

In [43]:
models_dict = get_models_dict(alpha=0.1, lr=1e-1, iters=5000, name='MinMaxScaler')
result_MMS_norm_MAE, result_MMS_norm_MSE, result_MMS_norm_r2, trained_models_MMS_norm = evaluate_models(
    X_train_final, Y_train_log, X_val_final, Y_val_log,
    models=models_dict, log_y=True)

In [44]:
result_MMS_norm_MAE

                                  model        train         test
0        my_linreg_analytical_nopenalty   539.090338   528.487064
1        my_linreg_stochastic_nopenalty   567.391195   559.389438
2    my_linreg_non-stochastic_nopenalty   563.165741   555.171416
3            my_linreg_analytical_lasso   539.090338   528.487064
4            my_linreg_stochastic_lasso  1078.329352  1066.083167
5        my_linreg_non-stochastic_lasso  1064.475921  1051.874068
6            my_linreg_analytical_ridge   539.090338   528.487064
7            my_linreg_stochastic_ridge   876.203006   864.150417
8        my_linreg_non-stochastic_ridge   866.512914   853.433471
9       my_linreg_analytical_elasticnet   539.090338   528.487064
10      my_linreg_stochastic_elasticnet  1013.876569  1000.790424
11  my_linreg_non-stochastic_elasticnet  1006.216225   993.417913
12               sk_linreg_MinMaxScaler   539.090353   528.487086
13                sk_lasso_MinMaxScaler  1089.815404  1077.320569
14                sk_ridge_MinMaxScaler   547.428183   536.921303
15           sk_elasticnet_MinMaxScaler  1074.865663  1062.295675

In [45]:
result_MMS_norm_MSE

                                  model        train         test
0        my_linreg_analytical_nopenalty   864.616554   829.321505
1        my_linreg_stochastic_nopenalty   910.871163   877.404886
2    my_linreg_non-stochastic_nopenalty   910.522722   877.537321
3            my_linreg_analytical_lasso   864.616554   829.321505
4            my_linreg_stochastic_lasso  1561.593310  1532.144853
5        my_linreg_non-stochastic_lasso  1581.322154  1551.167526
6            my_linreg_analytical_ridge   864.616554   829.321505
7            my_linreg_stochastic_ridge  1316.371863  1283.766422
8        my_linreg_non-stochastic_ridge  1331.185561  1298.459951
9       my_linreg_analytical_elasticnet   864.616554   829.321505
10      my_linreg_stochastic_elasticnet  1563.608108  1531.964734
11  my_linreg_non-stochastic_elasticnet  1508.696093  1477.196523
12               sk_linreg_MinMaxScaler   864.616528   829.321481
13                sk_lasso_MinMaxScaler  1614.321399  1584.947612
14                sk_ridge_MinMaxScaler   877.014082   842.300881
15           sk_elasticnet_MinMaxScaler  1598.128764  1568.178700

In [46]:
result_MMS_norm_r2

                                  model     train      test
0        my_linreg_analytical_nopenalty  0.704750  0.718456
1        my_linreg_stochastic_nopenalty  0.672315  0.684862
2    my_linreg_non-stochastic_nopenalty  0.672566  0.684767
3            my_linreg_analytical_lasso  0.704750  0.718456
4            my_linreg_stochastic_lasso  0.036884  0.039051
5        my_linreg_non-stochastic_lasso  0.012395  0.015041
6            my_linreg_analytical_ridge  0.704750  0.718456
7            my_linreg_stochastic_ridge  0.315616  0.325359
8        my_linreg_non-stochastic_ridge  0.300126  0.309827
9       my_linreg_analytical_elasticnet  0.704750  0.718456
10      my_linreg_stochastic_elasticnet  0.034397  0.039277
11  my_linreg_non-stochastic_elasticnet  0.101028  0.106741
12               sk_linreg_MinMaxScaler  0.704750  0.718456
13                sk_lasso_MinMaxScaler -0.029254 -0.028325
14                sk_ridge_MinMaxScaler  0.696222  0.709574
15           sk_elasticnet_MinMaxScaler -0.008709 -0.006681

In [47]:
models = ['sk_linreg_MinMaxScaler', 'sk_lasso_MinMaxScaler', 'sk_ridge_MinMaxScaler', 'sk_elasticnet_MinMaxScaler']

final_MAE = pd.concat([final_MAE, result_MMS_norm_MAE[result_MMS_norm_MAE['model'].isin(models)]])
final_MSE = pd.concat([final_MSE, result_MMS_norm_MSE[result_MMS_norm_MSE['model'].isin(models)]])
final_r2 = pd.concat([final_r2, result_MMS_norm_r2[result_MMS_norm_r2['model'].isin(models)]])

In [48]:
final_MAE

                         model        train         test
3                    sk-linreg   539.090353   528.487086
12                   sk_linreg   539.090353   528.487086
13                    sk_lasso   857.064538   842.414783
14                    sk_ridge   539.288264   528.844743
15               sk_elasticnet   749.149443   733.631215
12      sk_linreg_MinMaxScaler   539.090353   528.487086
13       sk_lasso_MinMaxScaler  1089.815404  1077.320569
14       sk_ridge_MinMaxScaler   547.428183   536.921303
15  sk_elasticnet_MinMaxScaler  1074.865663  1062.295675

- Ну StandardScaler был в пайплайне выше - можем воспроизвести

In [49]:
feature_transformer = make_pipeline(preprocessor, StandardScaler())
X_train_final = feature_transformer.fit_transform(X_train_new)
X_val_final = feature_transformer.transform(X_val_new)

In [50]:
models_dict = get_models_dict(alpha=0.1, lr=1e-4, iters=10000, name='StandardScaler', clip_value=1e-2)

result_SS_norm_MAE, result_SS_norm_MSE, result_SS_norm_r2, trained_models_SS_norm = evaluate_models(
    X_train_final, Y_train_log, X_val_final, Y_val_log,
    models=models_dict, log_y=True
)

In [51]:
result_SS_norm_MAE

                                  model       train        test
0        my_linreg_analytical_nopenalty  539.090353  528.487086
1        my_linreg_stochastic_nopenalty  975.619855  958.457163
2    my_linreg_non-stochastic_nopenalty  946.236527  932.900963
3            my_linreg_analytical_lasso  539.090353  528.487086
4            my_linreg_stochastic_lasso  976.742396  962.432135
5        my_linreg_non-stochastic_lasso  964.110689  951.047394
6            my_linreg_analytical_ridge  539.090353  528.487086
7            my_linreg_stochastic_ridge  943.916785  932.118568
8        my_linreg_non-stochastic_ridge  901.591425  888.860404
9       my_linreg_analytical_elasticnet  539.090353  528.487086
10      my_linreg_stochastic_elasticnet  949.985746  936.717927
11  my_linreg_non-stochastic_elasticnet  967.547560  953.606769
12             sk_linreg_StandardScaler  539.090353  528.487086
13              sk_lasso_StandardScaler  857.064538  842.414783
14              sk_ridge_StandardScaler  539.288264  528.844743
15         sk_elasticnet_StandardScaler  749.149443  733.631215

In [52]:
result_SS_norm_MSE

                                  model        train         test
0        my_linreg_analytical_nopenalty   864.616528   829.321481
1        my_linreg_stochastic_nopenalty  1703.706313  1435.954774
2    my_linreg_non-stochastic_nopenalty  1463.852171  1391.054633
3            my_linreg_analytical_lasso   864.616528   829.321481
4            my_linreg_stochastic_lasso  1470.764946  1440.563208
5        my_linreg_non-stochastic_lasso  1444.630116  1415.370035
6            my_linreg_analytical_ridge   864.616528   829.321481
7            my_linreg_stochastic_ridge  1446.297141  1436.006550
8        my_linreg_non-stochastic_ridge  1386.890755  1353.084584
9       my_linreg_analytical_elasticnet   864.616528   829.321481
10      my_linreg_stochastic_elasticnet  1411.198832  1382.067121
11  my_linreg_non-stochastic_elasticnet  1469.042968  1437.011617
12             sk_linreg_StandardScaler   864.616528   829.321481
13              sk_lasso_StandardScaler  1282.879609  1253.258488
14              sk_ridge_StandardScaler   865.042402   830.048269
15         sk_elasticnet_StandardScaler  1138.114351  1106.192269

In [53]:
result_SS_norm_r2

                                  model     train      test
0        my_linreg_analytical_nopenalty  0.704750  0.718456
1        my_linreg_stochastic_nopenalty -0.146389  0.155923
2    my_linreg_non-stochastic_nopenalty  0.153675  0.207884
3            my_linreg_analytical_lasso  0.704750  0.718456
4            my_linreg_stochastic_lasso  0.145663  0.150496
5        my_linreg_non-stochastic_lasso  0.175756  0.179949
6            my_linreg_analytical_ridge  0.704750  0.718456
7            my_linreg_stochastic_ridge  0.173852  0.155862
8        my_linreg_non-stochastic_ridge  0.240326  0.250536
9       my_linreg_analytical_elasticnet  0.704750  0.718456
10      my_linreg_stochastic_elasticnet  0.213463  0.218086
11  my_linreg_non-stochastic_elasticnet  0.147663  0.154680
12             sk_linreg_StandardScaler  0.704750  0.718456
13              sk_lasso_StandardScaler  0.349998  0.357043
14              sk_ridge_StandardScaler  0.704459  0.717962
15         sk_elasticnet_StandardScaler  0.488419  0.499087

In [54]:
models = ['sk_linreg_StandardScaler', 'sk_lasso_StandardScaler', 'sk_ridge_StandardScaler', 'sk_elasticnet_StandardScaler']

final_MAE = pd.concat([final_MAE, result_SS_norm_MAE[result_SS_norm_MAE['model'].isin(models)]])
final_MSE = pd.concat([final_MSE, result_SS_norm_MSE[result_SS_norm_MSE['model'].isin(models)]])
final_r2 = pd.concat([final_r2, result_SS_norm_r2[result_SS_norm_r2['model'].isin(models)]])

- Lasso, ElasticNet у меня сходятся хуже, чем реализации sklearn.

# 8. Overfit models

- Let's look at an overfitted model in practice. From theory, you know that polynomial regression is easy to overfit. So let's create a toy example and see how regularization works in real life.
- In the previous lesson, we created polynomial features with degree 10. Here we repeat these steps from the previous lesson, remembering that we have only 3 basic features — 'bathrooms', 'bedrooms', 'interest_level'.
- And train and fit all our implemented algorithms — Linear Regression, Ridge, Lasso, and ElasticNet — on a set of polynomial features.
- Store the results of the quality metrics in the result dataframe.
Analyze the results and select the best model according to your opinion.
- Additionally try different alpha parameters of regularization in algorithms, choose the best one and analyze results.

In [55]:
X_basic_features_train = X_train_new[['bathrooms', 'bedrooms', 'interest_level']].copy()
X_basic_features_test = X_val_new[['bathrooms', 'bedrooms', 'interest_level']].copy()

In [56]:
preprocessor = ColumnTransformer([
    ('cat', OneHotEncoder(drop='first', sparse_output=False), ["interest_level"])
])

In [57]:
feature_transformer = make_pipeline(preprocessor, StandardScaler())

X_basic_features_SS_train = feature_transformer.fit_transform(X_basic_features_train)
X_basic_features_SS_test= feature_transformer.transform(X_basic_features_test)

In [58]:
poly = PolynomialFeatures(10)
poly.fit_transform(X_basic_features_SS_train)

poly_X_train = poly.transform(X_basic_features_SS_train)
poly_X_test = poly.transform(X_basic_features_SS_test)

- Тут ожидаем переобучения, поэтому можно использовать и неотлогарифмированный таргет

In [59]:
models_dict = get_models_dict(name="Poly", lr=1e-4, iters=10000)
result_poly_MAE, result_poly_MSE, result_poly_r2, trained_models_poly = evaluate_models(
    poly_X_train, Y_train, poly_X_test, Y_val,
    models=models_dict, log_y=False
)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.204e+07, tolerance: 9.792e+06
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.130e+10, tolerance: 9.792e+06
  model = cd_fast.enet_coordinate_descent(

In [60]:
result_poly_MAE

                                  model         train          test
0        my_linreg_analytical_nopenalty  1.114806e+03  1.102899e+03
1        my_linreg_stochastic_nopenalty  1.064987e+21  1.064184e+21
2    my_linreg_non-stochastic_nopenalty  6.269747e+20  6.265017e+20
3            my_linreg_analytical_lasso  1.114806e+03  1.102899e+03
4            my_linreg_stochastic_lasso  5.324918e+20  5.320901e+20
5        my_linreg_non-stochastic_lasso  6.269747e+20  6.265017e+20
6            my_linreg_analytical_ridge  1.114806e+03  1.102899e+03
7            my_linreg_stochastic_ridge  1.064986e+21  1.064182e+21
8        my_linreg_non-stochastic_ridge  6.269745e+20  6.265015e+20
9       my_linreg_analytical_elasticnet  1.114806e+03  1.102899e+03
10      my_linreg_stochastic_elasticnet  5.324868e+20  5.320850e+20
11  my_linreg_non-stochastic_elasticnet  6.269747e+20  6.265017e+20
12                       sk_linreg_Poly  1.114806e+03  1.102899e+03
13                        sk_lasso_Poly  1.114806e+03  1.102899e+03
14                        sk_ridge_Poly  1.114806e+03  1.102899e+03
15                   sk_elasticnet_Poly  1.114806e+03  1.102899e+03

In [61]:
result_poly_MSE

                                  model         train          test
0        my_linreg_analytical_nopenalty  1.558860e+03  1.531389e+03
1        my_linreg_stochastic_nopenalty  3.925875e+21  3.924394e+21
2    my_linreg_non-stochastic_nopenalty  2.311224e+21  2.310352e+21
3            my_linreg_analytical_lasso  1.558860e+03  1.531389e+03
4            my_linreg_stochastic_lasso  1.962931e+21  1.962190e+21
5        my_linreg_non-stochastic_lasso  2.311224e+21  2.310352e+21
6            my_linreg_analytical_ridge  1.558860e+03  1.531389e+03
7            my_linreg_stochastic_ridge  3.925870e+21  3.924389e+21
8        my_linreg_non-stochastic_ridge  2.311223e+21  2.310351e+21
9       my_linreg_analytical_elasticnet  1.558860e+03  1.531389e+03
10      my_linreg_stochastic_elasticnet  1.962912e+21  1.962172e+21
11  my_linreg_non-stochastic_elasticnet  2.311224e+21  2.310352e+21
12                       sk_linreg_Poly  1.558860e+03  1.531389e+03
13                        sk_lasso_Poly  1.558860e+03  1.531389e+03
14                        sk_ridge_Poly  1.558860e+03  1.531389e+03
15                   sk_elasticnet_Poly  1.558860e+03  1.531389e+03

In [62]:
result_poly_r2

                                  model         train          test
0        my_linreg_analytical_nopenalty  4.025297e-02  3.999879e-02
1        my_linreg_stochastic_nopenalty -6.087172e+36 -6.304431e+36
2    my_linreg_non-stochastic_nopenalty -2.109730e+36 -2.185029e+36
3            my_linreg_analytical_lasso  4.025297e-02  3.999879e-02
4            my_linreg_stochastic_lasso -1.521782e+36 -1.576097e+36
5        my_linreg_non-stochastic_lasso -2.109730e+36 -2.185029e+36
6            my_linreg_analytical_ridge  4.025297e-02  3.999879e-02
7            my_linreg_stochastic_ridge -6.087156e+36 -6.304415e+36
8        my_linreg_non-stochastic_ridge -2.109728e+36 -2.185027e+36
9       my_linreg_analytical_elasticnet  4.025297e-02  3.999879e-02
10      my_linreg_stochastic_elasticnet -1.521754e+36 -1.576067e+36
11  my_linreg_non-stochastic_elasticnet -2.109729e+36 -2.185028e+36
12                       sk_linreg_Poly  4.025297e-02  3.999879e-02
13                        sk_lasso_Poly  4.025297e-02  3.999879e-02
14                        sk_ridge_Poly  4.025297e-02  3.999879e-02
15                   sk_elasticnet_Poly  4.025297e-02  3.999879e-02

In [63]:
models = ['sk_linreg_Poly', 'sk_lasso_Poly', 'sk_ridge_Poly', 'sk_elasticnet_Poly']

final_MAE = pd.concat([final_MAE, result_SS_norm_MAE[result_SS_norm_MAE['model'].isin(models)]])
final_MSE = pd.concat([final_MSE, result_SS_norm_MSE[result_SS_norm_MSE['model'].isin(models)]])
final_r2 = pd.concat([final_r2, result_SS_norm_r2[result_SS_norm_r2['model'].isin(models)]])

In [64]:
final_MAE

                           model        train         test
3                      sk-linreg   539.090353   528.487086
12                     sk_linreg   539.090353   528.487086
13                      sk_lasso   857.064538   842.414783
14                      sk_ridge   539.288264   528.844743
15                 sk_elasticnet   749.149443   733.631215
12        sk_linreg_MinMaxScaler   539.090353   528.487086
13         sk_lasso_MinMaxScaler  1089.815404  1077.320569
14         sk_ridge_MinMaxScaler   547.428183   536.921303
15    sk_elasticnet_MinMaxScaler  1074.865663  1062.295675
12      sk_linreg_StandardScaler   539.090353   528.487086
13       sk_lasso_StandardScaler   857.064538   842.414783
14       sk_ridge_StandardScaler   539.288264   528.844743
15  sk_elasticnet_StandardScaler   749.149443   733.631215

# 9. Naive models

- Calculate the mean and median metrics from the previous lesson and add the results to the final dataframe.

In [65]:
train_price_mean = np.mean(Y_train)
train_price_median = np.median(Y_train)

val_price_mean = np.mean(Y_val)
val_price_median  = np.median(Y_val)

In [66]:
## MAE on training between target and mean or median AND on test between target and mean or median
train_mean_mae = mean_absolute_error(Y_train, np.full_like(Y_train, train_price_mean))
train_median_mae = mean_absolute_error(Y_train, np.full_like(Y_train, train_price_median))
val_mean_mae = mean_absolute_error(Y_val, np.full_like(Y_val, val_price_mean))
val_median_mae = mean_absolute_error(Y_val, np.full_like(Y_val, val_price_median))

In [67]:
## RMSE on training between target and mean or median AND on test between target and mean or median
train_mean_mse = np.sqrt(mean_squared_error(Y_train, np.full_like(Y_train, train_price_mean)))
train_median_mse = np.sqrt(mean_squared_error(Y_train, np.full_like(Y_train, train_price_median)))
val_mean_mse = np.sqrt(mean_squared_error(Y_val, np.full_like(Y_val, val_price_mean)))
val_median_mse = np.sqrt(mean_squared_error(Y_val, np.full_like(Y_val, val_price_median)))

In [68]:
##r2
train_mean_r2 = r2_score(Y_train, np.full_like(Y_train, train_price_mean))
train_median_r2 = r2_score(Y_train, np.full_like(Y_train, train_price_median))
val_mean_r2 = r2_score(Y_val, np.full_like(Y_val, val_price_mean))
val_median_r2 = r2_score(Y_val, np.full_like(Y_val, val_price_median))

In [69]:
final_MAE = pd.concat([
    final_MAE,
    pd.DataFrame({
        'model': ['naive_mean', 'naive_median'],
        'train': [train_mean_mae, train_median_mae],
        'test': [val_mean_mae, val_median_mae]
    })
], ignore_index=True)

In [70]:
final_MSE = pd.concat([
    final_MSE,
    pd.DataFrame({
        'model': ['naive_mean', 'naive_median'],
        'train': [train_mean_mse, train_median_mse],
        'test': [val_mean_mse, val_median_mse]
    })
], ignore_index=True)

In [71]:
final_r2 = pd.concat([
    final_r2,
    pd.DataFrame({
        'model': ['naive_mean_r2', 'naive_median_r2'],
        'train': [train_mean_r2, train_median_r2],
        'test': [val_mean_r2, val_median_r2]
    })

], ignore_index=True)

# 10. Compare results

- Print your final tables
- What is the best model?
- Which is the most stable model?

In [72]:
final_MAE

                           model        train         test
0                      sk-linreg   539.090353   528.487086
1                      sk_linreg   539.090353   528.487086
2                       sk_lasso   857.064538   842.414783
3                       sk_ridge   539.288264   528.844743
4                  sk_elasticnet   749.149443   733.631215
5         sk_linreg_MinMaxScaler   539.090353   528.487086
6          sk_lasso_MinMaxScaler  1089.815404  1077.320569
7          sk_ridge_MinMaxScaler   547.428183   536.921303
8     sk_elasticnet_MinMaxScaler  1074.865663  1062.295675
9       sk_linreg_StandardScaler   539.090353   528.487086
10       sk_lasso_StandardScaler   857.064538   842.414783
11       sk_ridge_StandardScaler   539.288264   528.844743
12  sk_elasticnet_StandardScaler   749.149443   733.631215
13                    naive_mean  1137.014040  1122.444410
14                  naive_median  1084.733335  1072.171476

In [73]:
final_MSE

                           model        train         test
0                      sk-linreg   864.616528   829.321481
1                      sk_linreg   864.616528   829.321481
2                       sk_lasso  1282.879609  1253.258488
3                       sk_ridge   865.042402   830.048269
4                  sk_elasticnet  1138.114351  1106.192269
5         sk_linreg_MinMaxScaler   864.616528   829.321481
6          sk_lasso_MinMaxScaler  1614.321399  1584.947612
7          sk_ridge_MinMaxScaler   877.014082   842.300881
8     sk_elasticnet_MinMaxScaler  1598.128764  1568.178700
9       sk_linreg_StandardScaler   864.616528   829.321481
10       sk_lasso_StandardScaler  1282.879609  1253.258488
11       sk_ridge_StandardScaler   865.042402   830.048269
12  sk_elasticnet_StandardScaler  1138.114351  1106.192269
13                    naive_mean  1591.214781  1562.966777
14                  naive_median  1637.597067  1607.997940

In [74]:
final_r2

                           model         train          test
0                      sk-linreg  7.047502e-01  7.184559e-01
1                      sk_linreg  7.047502e-01  7.184559e-01
2                       sk_lasso  3.499985e-01  3.570430e-01
3                       sk_ridge  7.044593e-01  7.179622e-01
4                  sk_elasticnet  4.884191e-01  4.990875e-01
5         sk_linreg_MinMaxScaler  7.047502e-01  7.184559e-01
6          sk_lasso_MinMaxScaler -2.925401e-02 -2.832517e-02
7          sk_ridge_MinMaxScaler  6.962224e-01  7.095742e-01
8     sk_elasticnet_MinMaxScaler -8.709465e-03 -6.680707e-03
9       sk_linreg_StandardScaler  7.047502e-01  7.184559e-01
10       sk_lasso_StandardScaler  3.499985e-01  3.570430e-01
11       sk_ridge_StandardScaler  7.044593e-01  7.179622e-01
12  sk_elasticnet_StandardScaler  4.884191e-01  4.990875e-01
13                 naive_mean_r2 -3.864793e-07 -3.167278e-07
14               naive_median_r2 -5.914803e-02 -5.845310e-02

- лучшая модель - sk_ridge (обученная на кастомном пайплайне с StandardScaler), к ней близка sk_ridge_MinMaxScaler;
- стабильная модель - линейная регрессия на аналитическом решении (дает точный минимум за один шаг, не зависит от гиперпараметров, нечувствительно к масштабу признаков, находит минимум за конечное число итераций);
- но для больших данных аналитическое решение становится численно нестабильным;
- для градиентных методов необходимо подбирать гиперпараметры (особенно lr  и кол-во итераций).